// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARd5-fsWKv_v315R3LGDkvM7Y_P6mYweE',
    appId: '1:776553364910:web:d0b0d23021c8590bb79c3f',
    messagingSenderId: '776553364910',
    projectId: 'spotify7899',
    authDomain: 'spotify7899.firebaseapp.com',
    storageBucket: 'spotify7899.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1uAGcINMpO4vqykFJWQ2Ddttu1bT5Gpg',
    appId: '1:776553364910:android:c655240aa94e5008b79c3f',
    messagingSenderId: '776553364910',
    projectId: 'spotify7899',
    storageBucket: 'spotify7899.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq0QifG9FNiMDO9ayZGEXhZEGsaDJNVco',
    appId: '1:776553364910:ios:a16a7aa7cd268bc8b79c3f',
    messagingSenderId: '776553364910',
    projectId: 'spotify7899',
    storageBucket: 'spotify7899.firebasestorage.app',
    iosBundleId: 'com.example.spotifyNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq0QifG9FNiMDO9ayZGEXhZEGsaDJNVco',
    appId: '1:776553364910:ios:a16a7aa7cd268bc8b79c3f',
    messagingSenderId: '776553364910',
    projectId: 'spotify7899',
    storageBucket: 'spotify7899.firebasestorage.app',
    iosBundleId: 'com.example.spotifyNow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARd5-fsWKv_v315R3LGDkvM7Y_P6mYweE',
    appId: '1:776553364910:web:323538bb84cae00cb79c3f',
    messagingSenderId: '776553364910',
    projectId: 'spotify7899',
    authDomain: 'spotify7899.firebaseapp.com',
    storageBucket: 'spotify7899.firebasestorage.app',
  );
}
